# You have to download TEDLIUM "online nnet2" models in order to use this sample
# Run download-tedlium-nnet2.sh in 'test/models' to download them.
use-nnet2: True
decoder:
    use-threaded-decoder:  true
    model : test/models/vietname_v1/final.mdl
    nnet-mode: 3
    word-syms : test/models/vietname_v1/graph-big/words.txt
    fst : test/models/vietname_v1/graph-big/HCLG.fst
    mfcc-config : test/models/vietname_v1/conf/mfcc.conf
    ivector-extraction-config : test/models/vietname_v1/conf/ivector_extractor.conf
    min-active: 1000
    max-active: 10000
    beam: 21 #
    lattice-beam: 5 # 11
    inverse-scale: false
    acoustic-scale: 1.0 # AM=1/0.9~1.1
    phone-syms: test/models/vietname_v1/phones.txt
    do-endpointing : true
    endpoint-silence-phones : "1:2:3:4:5:26:27:28:29:30"
    silence-phones: "1:2:3:4:5:6:7:8:9:10:11:12:13:14:15:16:17:18:19:20:21:22:23:24:25:26:27:28:29:30"
    traceback-period-in-secs: 0.3
    chunk-length-in-secs: 0.25
    num-nbest: 2
    frame-subsampling-factor: 3
    # For rescoring
    lmwt-scale: 1.25
    #    lm-fst : model/CARPA-LM/G.fst
    #big-lm-const-arpa: model/CARPA-LM/G.carpa
out-dir: tmp
silence-timeout:  5

# Just a sample post-processor that appends "." to the hypothesis
#post-processor: perl -npe 'BEGIN {use IO::Handle; STDOUT->autoflush(1);} s/(.*)/\1./;'

# A sample full post processor that add a confidence score to 1-best hyp and deletes other n-best hyps
#full-post-processor: ./sample_full_post_processor.py
full-post-processor: ./sample_full_post_processor.py

logging:
    version : 1
    disable_existing_loggers: False
    formatters:
        simpleFormater:
            format: '%(asctime)s - %(levelname)7s: %(name)10s: %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        console:
            class: logging.StreamHandler
            formatter: simpleFormater
            level: DEBUG
    root:
        level: DEBUG
        handlers: [console]
